kony = kony || {};
kony.saveNextGen = kony.saveNextGen || {};
kony.saveNextGen.util = kony.saveNextGen.util || {};
kony.saveNextGen.util.formatDate = "YYYYMMDDHHMMSS";
kony.saveNextGen.util.eventData = [
       {
      "eventId" : "01",
      "eventDateTime": "22 May,2016",
      "date" : "2016-05-22",
      "location": {"place" : "APHB colony",
                   "street": "Gachibowli",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-8984445414",
      "time" : "4:30 PM",
      "saplingCount": "50",
      "eventName": "vanamahotsava",
      "volunteerCount": "5",
      "organisationName":"Kony Private Limited",
      "occation": "companyEvent",
      "latitude": "17.4466",
      "longitude" : "78.3573",
      "distance" : "2 Km away ",
      "distanceLabel" : "2 Km"
    },{
      "eventId" : "02",
      "eventDateTime": "04 Jan,2017",
      "date" : "2017-01-04",
      "location": {"place" : "Madhapur",
                   "street": "Image Hospitals Lane",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-8985448819",
      "time" : "5.00 PM",
      "saplingCount": "250",
      "eventName": "Make your Day",
      "volunteerCount": "7",
      "organisationName":"Make your Day Organisaiton",
      "occation": "Birthday",
      "latitude": "17.4483",
      "longitude" : "78.3915", 
      "distance" : "5 Km away ",
      "distanceLabel" : "5 Km"
    }, {
      "eventId" : "03",
      "eventDateTime": "13 Septemper,2016",
      "date" : "2016-09-13",
      "location": {"place" : "Botanical Garden",
                   "street": "Anjaiahnagar",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-8106389282",
      "time" : "10.00 AM",
      "saplingCount": "500",
      "eventName": "Make it Green",
      "volunteerCount": "50",
      "organisationName":"F5 NGO",
      "occation": "Green Day",
      "latitude": "17.46",
      "longitude" : "78.37",
      "distance" : "7 Km away ",
      "distanceLabel" : "7 Km"
    },{
      "eventId" : "04",
      "eventDateTime": "15 Aug,2016",
      "date" : "2016-08-15",
      "location": {"place" : "Near google Officce",
                   "street": "Kondapur",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-8984371289",
      "time" : "10:30 AM",
      "saplingCount": "100",
      "eventName": "Green India",
      "volunteerCount": "20",
      "organisationName":"Government of Telangana",
      "occation": "Independencce Day",
      "latitude": "17.44",
      "longitude" : "78.37",
      "distance" : "12 Km away ",
      "distanceLabel" : "12 Km"
    },{
      "eventId" : "05",
      "eventDateTime": "01 January,2017",
      "date" : "2017-01-01",
      "location": {"place" : "Near Infosys Campus",
                   "street": "Financial district",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-8414216969",
      "time" : "2:30 PM",
      "saplingCount": "150",
      "eventName": "Be the First on First",
      "volunteerCount": "25",
      "organisationName":"Infosys",
      "occation": "companyEvent",
      "latitude": "17.38",
      "longitude" : "78.48",
      "distance" : "12 Km away",
      "distanceLabel" : "12 Km"
    },
          {
      "eventId" : "06",
      "eventDateTime": "20 Deccember,2016",
      "date" : "2016-12-20",
      "location": {"place" : "Near TCS Adibatla",
                   "street": "Adibatla",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-7973456719",
      "time" : "03:30 PM",
      "saplingCount": "120",
      "eventName": "TCS Initiative",
      "volunteerCount": "12 to 15",
      "organisationName":"TCS",
      "occation": "companyEvent",
      "latitude": "17.38",
      "longitude" : "78.48",
      "distance" : "20 Km away",
      "distanceLabel" : "20 Km"
    },
         {
      "eventId" : "07",
      "eventDateTime": "07 July,2017",
      "date" : "2017-07-07",
      "location": {"place" : "Jubilee hills",
                   "street": "Jubilee hills",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-8107096973",
      "time" : "2:30 PM",
      "saplingCount": "50",
      "eventName": "Save trees",
      "volunteerCount": "10",
      "organisationName":"S7 NGO",
      "occation": "NGO Initiative",
      "latitude": "17.43",
      "longitude" : "78.40",
      "distance" : "10 Km away",
      "distanceLabel" : "10 Km"
    }, {
      "eventId" : "08",
      "eventDateTime": "02 June,2016",
      "date" : "2016-06-02",
      "location": {"place" : "Golkonda",
                   "street": "Golkonda",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber": "+91-9954627903",
      "time" : "8:30 AM",
      "saplingCount": "70",
      "eventName": "Mana Repati Kosam",
      "volunteerCount": "10 to 20",
      "organisationName":"Chai Bisket",
      "occation": "Telangana Formation Day",
      "latitude": "17.38",
      "longitude" : "78.40",
      "distance" : "22 Km away",
      "distanceLabel" : "22 Km"
    },
     {
      "eventId" : "09",
      "eventDateTime": "20 October,2016",
      "date" : "2016-10-20",
      "location": {"place" : "Bio diversity",
                   "street": "Gachibowli",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-7206934569",
      "time" : "9:30 AM",
      "saplingCount": "111",
      "eventName": "Pacha thoranam",
      "volunteerCount": "50",
      "organisationName":"Govt. Of Telangana",
      "occation": "Govt. Initiative",
      "latitude": "17.4291",
      "longitude" : "78.3765",
      "distance" : "9 Km away",
      "distanceLabel" : "9 Km"
    },
  {
      "eventId" : "10",
      "eventDateTime": "14 November,2016",
      "date" : "2016-11-14",
      "location": {"place" : "Near RED FM station",
                   "street": "Banjara hills",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-7206426929",
      "time" : "09:35 AM",
      "saplingCount": "935",
      "eventName": "Big Green Man Competition",
      "volunteerCount": "115",
      "organisationName":"Red FM",
      "occation": "Awareness Programme",
      "latitude": "17.41",
      "longitude" : "78.43",
      "distance" : "9.35 Km away",
      "distanceLabel" : "9.35 Km"
    },
      {
      "eventId" : "11",
      "eventDateTime": "27 May,2016",
      "date" : "2016-05-27",
      "location": {"place" : "Near RED FM station",
                   "street": "Banjara hills",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-7206426929",
      "time" : "09:35 AM",
      "saplingCount": "935",
      "eventName": "Big Green Man Competition",
      "volunteerCount": "115",
      "organisationName":"Red FM",
      "occation": "Awareness Programme",
      "latitude": "17.41",
      "longitude" : "78.43",
      "distance" : "9.35 Km away",
      "distanceLabel" : "9.35 Km"
    },
          {
      "eventId" : "12",
      "eventDateTime": "28 May,2016",
      "date" : "2016-05-28",
      "location": {"place" : "Near RED FM station",
                   "street": "Banjara hills",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-7206426929",
      "time" : "09:35 AM",
      "saplingCount": "935",
      "eventName": "Go Green",
      "volunteerCount": "115",
      "organisationName":"Red FM",
      "occation": "Awareness Programme",
      "latitude": "17.41",
      "longitude" : "78.43",
      "distance" : "9.35 Km away",
      "distanceLabel" : "9.35 Km"
    },
     {
      "eventId" : "13",
      "eventDateTime": "28 May,2016",
      "date" : "2016-05-28",
      "location": {"place" : "Bio diversity",
                   "street": "Gachibowli",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-7206934569",
      "time" : "9:30 AM",
      "saplingCount": "111",
      "eventName": "Pacha thoranam",
      "volunteerCount": "50",
      "organisationName":"Govt. Of Telangana",
      "occation": "Govt. Initiative",
      "latitude": "17.4291",
      "longitude" : "78.3765",
      "distance" : "9.35 Km away",
      "distanceLabel" : "9.35 Km"
    },
       {
      "eventId" : "14",
      "eventDateTime": "27 May,2016",
      "date" : "2016-05-27",
      "location": {"place" : "Bio diversity",
                   "street": "Gachibowli",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber" : "+91-7206934569",
      "time" : "9:30 AM",
      "saplingCount": "111",
      "eventName": "Pacha thoranam",
      "volunteerCount": "50",
      "organisationName":"Govt. Of Telangana",
      "occation": "Govt. Initiative",
      "latitude": "17.4291",
      "longitude" : "78.3765",
      "distance" : "9 Km away",
      "distanceLabel" : "9 Km"
    },
   {
      "eventId" : "15",
      "eventDateTime": "02 June,2016",
      "date" : "2016-06-02",
      "location": {"place" : "Golkonda",
                   "street": "Golkonda",
                   "city":"Hyderabad",
                   "country":"India"
                  },
      "contactNumber": "+91-9954627903",
      "time" : "8:30 AM",
      "saplingCount": "70",
      "eventName": "Mana Repati Kosam",
      "volunteerCount": "10 to 20",
      "organisationName":"Chai Bisket",
      "occation": "Telangana Formation Day",
      "latitude": "17.38",
      "longitude" : "78.40",
      "distance" : "2 Km away",
      "distanceLabel" : "2 Km"
    }
    ];